/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.bancolombia.service.verifyaccountowner.api;

import co.com.bancolombia.service.verifyaccountowner.model.JsonApiBody;
import co.com.bancolombia.service.verifyaccountowner.model.VerifyAccountError;
import co.com.bancolombia.service.verifyaccountowner.model.VerifyAccountResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-11T14:17:45.456Z")
@Api(value = "verifyAccountOwner", description = "the verifyAccountOwner API")
public interface VerifyAccountOwnerApi {

    @ApiOperation(value = "Verify Account Owner", nickname = "verifyAccountOwner", notes = "Verify if beneficiary is own of account", response = VerifyAccountResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Beneficiary is account owner", response = VerifyAccountResponse.class),
        @ApiResponse(code = 405, message = "Invalid Input. please put correct request", response = VerifyAccountError.class) })
    @RequestMapping(value = "/verifyAccountOwner",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<VerifyAccountResponse> verifyAccountOwner(@ApiParam(value = "", required = true) @Valid @RequestBody JsonApiBody body);
}
